# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Juanru\Desktop\Python_Test\resources\main_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(281, 250)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, -5, 281, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setObjectName("gridLayout")
        self.labelEvenOdd = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("LM Roman 12")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelEvenOdd.setFont(font)
        self.labelEvenOdd.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelEvenOdd.setAutoFillBackground(False)
        self.labelEvenOdd.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEvenOdd.setObjectName("labelEvenOdd")
        self.gridLayout.addWidget(self.labelEvenOdd, 0, 0, 1, 1)
        self.spinBoxAmount = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBoxAmount.setObjectName("spinBoxAmount")
        self.gridLayout.addWidget(self.spinBoxAmount, 1, 0, 1, 1)
        self.pushButtonReset = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButtonReset.setAutoDefault(True)
        self.pushButtonReset.setDefault(False)
        self.pushButtonReset.setFlat(False)
        self.pushButtonReset.setObjectName("pushButtonReset")
        self.gridLayout.addWidget(self.pushButtonReset, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 281, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelEvenOdd.setText(_translate("MainWindow", "TextLabel"))
        self.pushButtonReset.setText(_translate("MainWindow", "Resetear"))
